name: grocery_app
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.8.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  share_plus: ^12.0.0
  image_picker: ^1.0.7
  dio: ^5.8.0+1
  webview_flutter: ^4.13.0
  flutter_local_notifications: ^19.4.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  order_tracker: ^0.0.2
  device_info_plus: ^12.1.0
  path_provider: ^2.1.2
  pinput: ^5.0.2
  permission_handler: ^12.0.1
  open_filex: ^4.7.0
  connectivity_plus: ^6.1.0
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.3.1
  logger: ^2.7.0
  equatable: ^2.0.7
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.1.0
  google_sign_in: ^6.2.1
  palette_generator: ^0.3.3+4
  flutter_html: ^3.0.0

  go_router: ^15.1.2
  get_it: ^8.0.3
  app_links: ^6.4.0
  http_certificate_pinning: ^3.0.1

  collection: any
  sign_in_with_apple: ^7.0.1
  device_preview: any
  image_cropper: ^12.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/icons/account_icons/
    - assets/icons/app_icons/
    - assets/images/OnBoarding/
    - .env

  fonts:
    - family: MADEOKineSans
      fonts:
        - asset: assets/fonts/made-okine-sans-personal-use.light.otf
          weight: 900

flutter_launcher_icons:
  image_path: "assets/icons/app_icons/splash_icon.jpeg"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/app_icons/splash_icon.jpeg
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  android_12:
    color: "#FFFFFF"
    image: assets/icons/app_icons/splash_icon.jpeg
