// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9heNRcUmey1lY2_UGSCuZrdViksKoG2E',
    appId: '1:356514741847:web:056ced79df340a9c4dad12',
    messagingSenderId: '356514741847',
    projectId: 'anaadapp',
    authDomain: 'anaadapp.firebaseapp.com',
    storageBucket: 'anaadapp.firebasestorage.app',
    measurementId: 'G-0FD3CY2PWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAACEio5BqvGQUhd6ag5T3CvXyHfyNfug',
    appId: '1:356514741847:android:8b14ff4944522e144dad12',
    messagingSenderId: '356514741847',
    projectId: 'anaadapp',
    storageBucket: 'anaadapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRh5uSAo29ylAiBxuBQU8jL5VKJtjdWaU',
    appId: '1:356514741847:ios:9749852aa134d0484dad12',
    messagingSenderId: '356514741847',
    projectId: 'anaadapp',
    storageBucket: 'anaadapp.firebasestorage.app',
    iosBundleId: 'com.example.anaadfoodsui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRh5uSAo29ylAiBxuBQU8jL5VKJtjdWaU',
    appId: '1:356514741847:ios:9749852aa134d0484dad12',
    messagingSenderId: '356514741847',
    projectId: 'anaadapp',
    storageBucket: 'anaadapp.firebasestorage.app',
    iosBundleId: 'com.example.anaadfoodsui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9heNRcUmey1lY2_UGSCuZrdViksKoG2E',
    appId: '1:356514741847:web:fb44470930ad4df54dad12',
    messagingSenderId: '356514741847',
    projectId: 'anaadapp',
    authDomain: 'anaadapp.firebaseapp.com',
    storageBucket: 'anaadapp.firebasestorage.app',
    measurementId: 'G-8WQ8XQEZ66',
  );
}
